### ISSUE TITLE
Use 'command -v' instead of 'which' in .zshrc

### ISSUE THREAD

**Issue by ghost** [kabirbg/dotfiles#1]
Idk if you want opinions / care about this, but `command` is POSIX + a shell builtin, and runs ~27 times faster than `which`.  The EDITOR environment variable definition could also be placed in .(z)profile if you want it to be faster.

**Comment by kabirbg** [comment]
Good idea, just fixed that — probably keeping it in zshrc for now because i haven't created a zprofile yet (probably will soon). thanks!
